### PR TITLE
display email address and phone number if these fields don’t have label

### PR DESCRIPTION
**Pull request by krezzoid**
display email address and phone number if these fields don’t have label

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Thanks for the PR. Can you briefly explain to me what the purpose of displaying these empty labels is?

**Comment by krezzoid** [comment]
Hi,

This issue appears if your contact "came" from Facebook/Twitter integration - in this case label field will be empty. Take look attached screenshots - here is I marked my contacts who came from Facebook/Twitter integration and label fields in this case will be empty, as result in your library you don't store for Contact any information about their emails.

Contacts without email information:
img_3882

But here now we can see email info:
img_3883

**Comment by AnthonyMDev** [comment]
Great. Thank you so much!

**Comment by AnthonyMDev** [comment]
`1.0.1` with this fix has been pushed.

**Pull request merged**
